spring.application.name=socialvibe-app
spring.datasource.url=jdbc:postgresql://localhost:5432/socialvibedb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=c2VjcmV0LWtleS1mb3Itc29jaWFsdmliZS1hcHBAMTcxMQ==
# JWT Token expiration time in milliseconds (7 days = 7 * 24 * 60 * 60 * 1000 = 604800000)
jwt.expiration=604800000

 file.upload-dir=uploads/

# Max size for a single file
spring.servlet.multipart.max-file-size=10MB

# Max size for the entire multipart request (files + JSON data)
spring.servlet.multipart.max-request-size=50MB

app.base-url=http://localhost:8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.mts.socialvibe_app=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/socialvibe-app.log
logging.file.max-size=10MB
logging.file.max-history=30